[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"

[functions]
  external_node_modules = ["express"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
