[build]
  functions = "functions"

[functions]
  external_node_modules = ["express", "axios", "body-parser", "dotenv", "ejs", "serverless-http"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
